config/routes.rb
Rails.application.routes.draw do
    resources :requests
    resources :moviments
    resources :messages


    get '/minhas-solicitacoes',                                       to: 'requests#my_requests',                 as: 'my_requests'
    get '/cancelar-solicitacao/:id',                                  to: 'requests#cancel_my_request',           as: 'cancel_my_request'
    put '/aprovar-solicitacao/:id',                                   to: 'requests#approve_request',             as: 'approve_request'
    put '/confirmacao-da-solicitacao/:id',                            to: 'requests#confirmation_request',        as: 'confirmation_request'

    


    root 'site#index'
    get '/empresas',                                                  to: 'site#empresas',                        as: 'empresas'
    get '/produtos_disponiveis/:id',                                  to: 'site#available_products',              as: 'available_products'
    
    #get '/termos-e-condicoes',                                        to: 'site#terms_and_conditios',             as: 'terms_and_conditios'
    
    devise_for :users, controllers: {
        sessions: 'users/sessions'
    }
    
    resources :users, only: [:index, :show, :new, :edit]
    get 'users/active_and_inactive_user/:id',                         to: 'users#active_and_inactive_user',       as: 'active_and_inactive_user'
    get 'users/active_and_inactive_profile/:id',                      to: 'users#active_and_inactive_profile',    as: 'active_and_inactive_profile'
    get 'users/aprove_profile/:id',                                   to: 'users#aprove_profile',                  as: 'aprove_profile'
    
    
    
    
    
    get '/pagamentos',                                                to: 'invoices#index',                       as: 'invoices'
    get '/vendas',                                                    to: 'invoices#sales',                       as: 'sales'
    get '/minhas_compras',                                            to: 'invoices#purchases',                   as: 'purchases'
    get '/recibo/:id',                                                to: 'invoices#recibo',                      as: 'recibo'
    get '/adc_details/:id',                                           to: 'invoices#adc_details',                 as: 'adc_details'
    
    
    
    get '/stores/:id/validate_cart/:pre_order_id',                    to: 'stores#validate_cart',                 as: 'validate_cart'
    post '/stores/:id/validate_code_and_finish/:pre_order_id',        to: 'stores#validate_code_and_finish',       as: 'validate_code_and_finish'
    get '/stores/:id/invoice_details/:factura_id',                    to: 'stores#invoice_details',               as: 'invoice_details'
    
    get '/detalhes_da_venda/:factura_id',                             to: 'invoices#details',                     as: 'details'
    get '/detalhes_da_compra/:factura_id',                            to: 'invoices#details_purchase',            as: 'details_purchase'
    get '/detalhes_da_factura/:factura_id',                           to: 'invoices#show',                        as: 'details_invoice'
    
    get '/stores/:id/remove_item_order/:item_order_id',               to: 'stores#remove_item_order',             as: 'remove_item_order'
    get '/stores/:id/consult_request',                                to: 'stores#consult_request',               as: 'consult_request'
    post '/stores/:id/add_product_to_list/:pre_order_id',             to: 'stores#add_product_to_list',           as: 'add_product_to_list'
    get '/stores/:id/details_of_current_order/:pre_order_id',         to: 'stores#details_of_current_order',      as: 'details_of_current_order'
    
    get '/dashboard',                                                 to: 'dashboard#index',                      as: 'dashboard'
    get '/validate_cell_phone_number',                                to: 'dashboard#validate_cell_phone_number', as: 'validate_cell_phone_number'
    

    get 'profiles/validate_profile/:id',                               to: 'profiles#validate_profile',             as: 'validate_profile'
    get 'profiles/rejected_profile/:id',                               to: 'profiles#rejected_profile',             as: 'rejected_profile'
    get 'profiles/details/:id',                                        to: 'profiles#details',                      as: 'profiles_details'
    get 'profiles/active_edit/:id',                                    to: 'profiles#active_edit',                  as: 'active_edit'
    get 'profiles/unlock_account/:id',                                 to: 'profiles#unlock_account',               as: 'unlock_account'
    put 'profiles/:id',                                                to: 'profiles#reduce',                       as: 'reduce'
    post 'adc_subscribed',                                             to: 'profiles#adc_subscribed',               as: 'adc_subscribed'
    

    get 'clientes/pendentes',                                         to: 'profiles#profiles_pending',              as: 'profiles_pending'
    get 'clientes/activos',                                           to: 'profiles#profiles_active',               as: 'profiles_active'
    get 'clientes/rejeitados',                                        to: 'profiles#profiles_rejecteds',            as: 'profiles_rejecteds'
    get 'clientes/bloqueados',                                        to: 'profiles#profiles_blockeds',             as: 'profiles_blockeds'
    
    
    get 'companies/details/:id',                                      to: 'companies#details',                    as: 'comapnies_details'
    get 'company/show_and_hidden_in_site/:id',                        to: 'companies#show_and_hidden_in_site',    as: 'show_and_hidden_in_site'
    get 'company/associate_user_company/:id',                         to: 'companies#associate_user_company',    as: 'associate_user_company'
    get 'company/reset-password/:id',                                 to: 'companies#reset_password_company_user',    as: 'reset_password_company_user'
    
    
    resources :admins                                                 #only: [:edit, :update]
    get 'admins/details/:id',                                         to: 'admins#details',                       as: 'admins_details'
    
    
    resources :publicities
    get 'publicity/show_pub_on_client/:id',                           to: 'publicities#show_pub_on_client',       as: 'show_pub_on_client'
    
    
    resources :partners
    get 'partner/show_and_hide_partner/:id',                          to: 'partners#show_and_hide_partner',       as: 'show_and_hide_partner'
    
    resources :categories
    resources :banks
    resources :products
    resources :stores
    resources :occupation_areas

    resources :companies do
        resources :bank_accounts, module: :companies
    end

    resources :configurations, only: [:edit, :update, :show] do
        resources :bank_accounts, module: :configurations
    end

    resources :profiles do
        resources :bank_accounts, module: :profiles
    end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :set_publicity


    def index
        @publicities = Publicity.all.where(status: true)

        puts "=================="
        #p current_user.sign_in_count
        puts "=================="

        #redirect_to edit_user_password_path if current_user.sign_in_count == 0


        if current_user.admin?
            @companies = Company.all
            @profiles = Profile.all
        end

        if current_user.customer?
            
            @validate_cell_phone_number_text = "Por favor inserir o código de confirmação, enviado por SMS"
            @products = Product.all
            @invoices = Factura.all
            @stores = Store.all

            @profile = current_user.profile
        end
    end

    def validate_cell_phone_number
        if params[:sms_code].length == 4
            if ValidationCode.validation(current_user, params[:sms_code])
                current_user.update_confirmation_cell_phone
                redirect_to root_path, notice: 'Conta validada com sucesso.'
            else
                @validate_cell_phone_number_text = "Código inválido"
            end
        else
            @validate_cell_phone_number_text = "Código inválido"
        end
    end


    private
        def set_publicity
            @publicity = Publicity.all
        end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_admin.html.erb
<!-- Hero -->
<div class="bg-image overflow-hidden" style="background-image: url('/home.svg');">
    <div class="bg-primary-dark-op">
        <div class="content content-narrow content-full">
            <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center mt-5 mb-2 text-center text-sm-left">
                <div class="flex-sm-fill">
                    <h1 class="font-w600 text-white mb-0 invisible" data-toggle="appear">Paga3</h1>
                    <h2 class="h4 font-w400 text-white-75 mb-0 invisible" data-toggle="appear" data-timeout="250">Seja bem-vindo à área administrativa</h2>
                </div>
                <div class="flex-sm-00-auto mt-3 mt-sm-0 ml-sm-3">
        
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Hero -->

<!-- Page Content -->
<div class="content content-narrow">
    <!-- Stats -->
    <div class="row">
        <div class="col-6 col-md-3 col-lg-6 col-xl-3">
            <a class="block block-rounded block-link-pop border-left border-primary border-4x" href="javascript:void(0)">
                <div class="block-content block-content-full bg-p3">
                    <div class="font-size-sm font-w600 text-uppercase text-muted">Clientes registados</div>
                    <div class="font-size-h2 font-w400 text-dark"><%= @profiles.count %></div>
                </div>
            </a>
        </div>

        <div class="col-6 col-md-3 col-lg-6 col-xl-3">
            <a class="block block-rounded block-link-pop border-left border-primary border-4x" href="javascript:void(0)">
                <div class="block-content block-content-full bg-p3">
                    <div class="font-size-sm font-w600 text-uppercase text-muted">Clientes activos</div>
                    <div class="font-size-h2 font-w400 text-dark"><%= @profiles.where(status: 1).count %></div>
                </div>
            </a>
        </div>
        <div class="col-6 col-md-3 col-lg-6 col-xl-3">
            <a class="block block-rounded block-link-pop border-left border-primary border-4x" href="javascript:void(0)">
                <div class="block-content block-content-full bg-p3">
                    <div class="font-size-sm font-w600 text-uppercase text-muted">Empresas</div>
                    <div class="font-size-h2 font-w400 text-dark"><%= @companies.count %></div>
                </div>
            </a>
        </div>

        <div class="col-6 col-md-3 col-lg-6 col-xl-3">
            <a class="block block-rounded block-link-pop border-left border-primary border-4x" href="javascript:void(0)">
                <div class="block-content block-content-full bg-p3">
                    <div class="font-size-sm font-w600 text-uppercase text-muted">Média de vendas</div>
                    <div class="font-size-h2 font-w400 text-dark">0</div>
                </div>
            </a>
        </div>
    </div>
    <!-- END Stats -->

    <!-- Dashboard Charts -->
    <div class="row">
        <div class="col-lg-6">
            <div class="block block-rounded block-mode-loading-oneui">
                <div class="block-header">
                    <h3 class="block-title">Ganhos em KZ</h3>
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-toggle="block-option" data-action="state_toggle" data-action-mode="demo">
                            <i class="si si-refresh"></i>
                        </button>
                        <button type="button" class="btn-block-option">
                            <i class="si si-settings"></i>
                        </button>
                    </div>
                </div>
                <div class="block-content p-0 bg-body-light text-center">
                    <div class="pt-3" style="height: 360px;"><canvas class="js-chartjs-dashboard-earnings"></canvas></div>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="block block-rounded block-mode-loading-oneui">
                <div class="block-header">
                    <h3 class="block-title">Vendas</h3>
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-toggle="block-option" data-action="state_toggle" data-action-mode="demo">
                            <i class="si si-refresh"></i>
                        </button>
                        <button type="button" class="btn-block-option">
                            <i class="si si-settings"></i>
                        </button>
                    </div>
                </div>
                <div class="block-content p-0 bg-body-light text-center">
                    <!-- Chart.js is initialized in js/pages/be_pages_dashboard.min.js which was auto compiled from _es6/pages/be_pages_dashboard.js) -->
                    <!-- For more info and examples you can check out http://www.chartjs.org/docs/ -->
                    <div class="pt-3" style="height: 360px;"><canvas class="js-chartjs-dashboard-sales"></canvas></div>
                </div>
            </div>
        </div>
    </div>
    <!-- END Dashboard Charts -->

</div>
<!-- END Page Content -->

app/views/dashboard/_company.html.erb
<!-- Hero -->
<div class="bg-image overflow-hidden" style="background-image: url('/home.svg');">
    <div class="bg-primary-dark-op">
        <div class="content content-narrow content-full">
            <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center mt-5 mb-2 text-center text-sm-left">
                <div class="flex-sm-fill">
                    <h1 class="font-w600 text-white mb-0 invisible" data-toggle="appear">Dashboard empresa</h1>
                    <h2 class="h4 font-w400 text-white-75 mb-0 invisible" data-toggle="appear" data-timeout="250">Seja bem-vindo</h2>
                </div>
                <div class="flex-sm-00-auto mt-3 mt-sm-0 ml-sm-3">
                    <span class="d-inline-block invisible" data-toggle="appear" data-timeout="350">
                    <h1 class="font-w600 text-white mb-0 invisible" data-toggle="appear"><%= current_user.sign_in_count %></h1>

                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Hero -->
<div class="content content-narrow">
    <!-- Stats -->
    <div class="row">
        <div class="col-4 col-md-4 col-lg-4 col-xl-4">
            <a class="block block-rounded block-link-pop border-left border-primary border-4x" href="<%= stores_path %>">
                <div class="block-content block-content-full bg-p3">
                    <div class="shadow card-icon"><i class="fas fa-store-alt font-size-lg"></i></div>
                    <div class="font-size-sm font-w600 text-uppercase text-muted">lojas</div>
                    <div class="font-size-h2 font-w400 text-dark"><%= current_user.company.stores.count %></div>
                </div>
            </a>
        </div>

        <div class="col-4 col-md-4 col-lg-4 col-xl-4">
            <a class="block block-rounded block-link-pop border-left border-primary border-4x" href="javascript:void(0)">
                <div class="block-content block-content-full bg-p3">
                    <div class="shadow card-icon"><i class="fab fa-product-hunt"></i></div>
                    <div class="font-size-sm font-w600 text-uppercase text-muted">produtos</div>
                    <div class="font-size-h2 font-w400 text-dark"><%= current_user.company.products.count %></div>
                </div>
            </a>
        </div>

        <div class="col-4 col-md-4 col-lg-4 col-xl-4">
            <a class="block block-rounded block-link-pop border-left border-primary border-4x" href="<%= sales_path %>">
                <div class="block-content block-content-full bg-p3">
                    <div class="shadow card-icon"><i class="fas fa-file-invoice"></i></div>
                    <div class="font-size-sm font-w600 text-uppercase text-muted">facturas processadas</div>
                    <div class="font-size-h2 font-w400 text-dark"><%= current_user.company.facturas.count %></div>
                </div>
            </a>
        </div>
    </div>
    <!-- END Stats -->
</div>

app/views/dashboard/_customer.html.erb
<!-- Hero -->
<div class="bg-image overflow-hidden" style="background-image: url('/home.svg');">
    <div class="bg-primary-dark-op">
        <div class="content content-narrow content-full">
            <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center mt-5 mb-2 text-center text-sm-left">
                <div class="flex-sm-fill">
                    <h1 class="font-w600 text-white mb-0 invisible" data-toggle="appear">Olá</h1>
                    <h2 class="h4 font-w400 text-white-75 mb-0 invisible" data-toggle="appear" data-timeout="250"><%= current_user.profile.name %></h2>
                </div>

                <div class="flex-sm-00-auto mt-3 mt-sm-0 ml-sm-3">
                    <% if current_user.profile.active? && @profile.adc_subscribed.attached? %>
                        <p>
                            <span class="d-inline-block invisible" data-toggle="appear" data-timeout="350">
                                <a class="btn btn-p3 px-4 py-2 btn-sm" data-toggle="click-ripple" href="<%= new_request_path %>">
                                    <i class="fa fa-plus mr-1"></i> Fazer compras
                                </a>
                            </span>
                        </p>
                    <% end %>

                    <% if @profile.adc_subscribed.attached? %>
                        <%= link_to rails_blob_path(@profile.adc_subscribed, disposition: 'attachment'), class: "text-white", target: :blank do %>
                            <span class="fa fa-file-pdf "></span> Baixar ADC assinada
                        <% end %>
                    <% else %>
                        <% if current_user.profile.active? && current_user.profile.iban.present? && current_user.profile.account_number.present? %>
                            <%= link_to adc_details_url(current_user.profile.adc, format: "pdf"), target: "_blank", class: "btn btn-sm btn-p3 text-right" do %>
                                <i class="fa fa-print mr-1"></i> Baixar ADC                    
                            <% end %>
                        <% else %>
                            <h4 class="alert-heading text-red font-w300 my-2 text-right">Por favor adicionar a conta bancária</h4>
                        <% end %>
                    <% end %>
                    
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Hero -->

<!-- Page Content -->
<div class="content content-narrow">
    <%= render "dashboard/customer/pending_account" if current_user.profile.pending? %>
    <%= render "dashboard/customer/active_account" if current_user.profile.active? %>
</div>
<!-- END Page Content -->

app/views/dashboard/index.html.erb
<% if current_user.admin? %>
    <%= render "dashboard/admin" %>
<% end %>

<% if current_user.customer? %>
    <% unless current_user.confirmation_cell_phone %>
        <%= render "dashboard/customer/confirmation_cell_phone" %>
    <% else %>
        <%= render "dashboard/customer" %>
    <% end %>
<% end %>

<% if current_user.company? %>
    <%= render "dashboard/company" %>
<% end %>

app/views/dashboard/search_identity_number.html.erb
<!-- Hero -->
<div class="bg-image overflow-hidden" style="background-image: url('/home.svg');">
    <div class="bg-primary-dark-op">
        <div class="content content-narrow content-full">
            <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center mt-5 mb-2 text-center text-sm-left">
                <div class="flex-sm-fill">
                    <h1 class="font-w600 text-white mb-0 invisible" data-toggle="appear">Olá</h1>
                    <h2 class="h4 font-w400 text-white-75 mb-0 invisible" data-toggle="appear" data-timeout="250"><%= current_user.email %></h2>
                </div>

                <div class="flex-sm-00-auto mt-3 mt-sm-0 ml-sm-3">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Hero -->

<div class="content content-narrow">
    <div class="row justify-content-md-center">
        <div class="col-4">
            <%= form_tag(search_identity_number_path, :method => "get", id: "search-form") do %>
                <div class="form-row">
                    <div class="col-md-8">
                        <%= text_field_tag :search_identity_number, params[:search_identity_number], placeholder: "Digite o nº de BI válido", class: "form-control mr-2" %>
                    </div>

                    <div class="col-md-2 text-left">
                        <%= submit_tag "Buscar", class: "btn btn-primary" %>
                    </div>
                </div>
            <% end %>
        </div>

        <div class="col-3">
            <div class="text-left">
                <p> <%= @search_identity_text %> </p>
            </div>
        </div>
    </div>

</div>

app/views/dashboard/validate_cell_phone_number.html.erb
<!-- Hero -->
<div class="bg-image overflow-hidden" style="background-image: url('/home.svg');">
    <div class="bg-primary-dark-op">
        <div class="content content-narrow content-full">
            <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center mt-5 mb-2 text-center text-sm-left">
                <div class="flex-sm-fill">
                    <h1 class="font-w600 text-white mb-0 invisible" data-toggle="appear">Olá</h1>
                    <h2 class="h4 font-w400 text-white-75 mb-0 invisible" data-toggle="appear" data-timeout="250"><%= current_user.email %></h2>
                </div>

                <div class="flex-sm-00-auto mt-3 mt-sm-0 ml-sm-3">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Hero -->

<div class="content content-narrow">
    <div class="row justify-content-md-center">
        <div class="col-4">
            <%= form_tag(validate_cell_phone_number_path, :method => "get", id: "search-form") do %>
                <div class="form-row">
                    <div class="col-md-8">
                        <%= text_field_tag :sms_code, 
                            params[:sms_code], 
                            placeholder: "Digite o código de válidação", 
                            class: "form-control mr-2" 
                        %>
                    </div>

                    <div class="col-md-2 text-left">
                        <%= submit_tag "Validar", class: "btn btn-primary" %>
                    </div>
                </div>
            <% end %>
        </div>

        <div class="col-3">
            <div class="text-left">
                <p> <%= @validate_cell_phone_number_text %> </p>
            </div>
        </div>
    </div>
</div>