config/routes.rb
Rails.application.routes.draw do
    resources :requests
    resources :moviments
    resources :messages


    get '/minhas-solicitacoes',                                       to: 'requests#my_requests',                 as: 'my_requests'
    get '/cancelar-solicitacao/:id',                                  to: 'requests#cancel_my_request',           as: 'cancel_my_request'
    put '/aprovar-solicitacao/:id',                                   to: 'requests#approve_request',             as: 'approve_request'
    put '/confirmacao-da-solicitacao/:id',                            to: 'requests#confirmation_request',        as: 'confirmation_request'

    


    root 'site#index'
    get '/empresas',                                                  to: 'site#empresas',                        as: 'empresas'
    get '/produtos_disponiveis/:id',                                  to: 'site#available_products',              as: 'available_products'
    
    #get '/termos-e-condicoes',                                        to: 'site#terms_and_conditios',             as: 'terms_and_conditios'
    
    devise_for :users, controllers: {
        sessions: 'users/sessions'
    }
    
    resources :users, only: [:index, :show, :new, :edit]
    get 'users/active_and_inactive_user/:id',                         to: 'users#active_and_inactive_user',       as: 'active_and_inactive_user'
    get 'users/active_and_inactive_profile/:id',                      to: 'users#active_and_inactive_profile',    as: 'active_and_inactive_profile'
    get 'users/aprove_profile/:id',                                   to: 'users#aprove_profile',                  as: 'aprove_profile'
    
    
    
    
    
    get '/pagamentos',                                                to: 'invoices#index',                       as: 'invoices'
    get '/vendas',                                                    to: 'invoices#sales',                       as: 'sales'
    get '/minhas_compras',                                            to: 'invoices#purchases',                   as: 'purchases'
    get '/recibo/:id',                                                to: 'invoices#recibo',                      as: 'recibo'
    get '/adc_details/:id',                                           to: 'invoices#adc_details',                 as: 'adc_details'
    
    
    
    get '/stores/:id/validate_cart/:pre_order_id',                    to: 'stores#validate_cart',                 as: 'validate_cart'
    post '/stores/:id/validate_code_and_finish/:pre_order_id',        to: 'stores#validate_code_and_finish',       as: 'validate_code_and_finish'
    get '/stores/:id/invoice_details/:factura_id',                    to: 'stores#invoice_details',               as: 'invoice_details'
    
    get '/detalhes_da_venda/:factura_id',                             to: 'invoices#details',                     as: 'details'
    get '/detalhes_da_compra/:factura_id',                            to: 'invoices#details_purchase',            as: 'details_purchase'
    get '/detalhes_da_factura/:factura_id',                           to: 'invoices#show',                        as: 'details_invoice'
    
    get '/stores/:id/remove_item_order/:item_order_id',               to: 'stores#remove_item_order',             as: 'remove_item_order'
    get '/stores/:id/consult_request',                                to: 'stores#consult_request',               as: 'consult_request'
    post '/stores/:id/add_product_to_list/:pre_order_id',             to: 'stores#add_product_to_list',           as: 'add_product_to_list'
    get '/stores/:id/details_of_current_order/:pre_order_id',         to: 'stores#details_of_current_order',      as: 'details_of_current_order'
    
    get '/dashboard',                                                 to: 'dashboard#index',                      as: 'dashboard'
    get '/validate_cell_phone_number',                                to: 'dashboard#validate_cell_phone_number', as: 'validate_cell_phone_number'
    

    get 'profiles/validate_profile/:id',                               to: 'profiles#validate_profile',             as: 'validate_profile'
    get 'profiles/rejected_profile/:id',                               to: 'profiles#rejected_profile',             as: 'rejected_profile'
    get 'profiles/details/:id',                                        to: 'profiles#details',                      as: 'profiles_details'
    get 'profiles/active_edit/:id',                                    to: 'profiles#active_edit',                  as: 'active_edit'
    get 'profiles/unlock_account/:id',                                 to: 'profiles#unlock_account',               as: 'unlock_account'
    put 'profiles/:id',                                                to: 'profiles#reduce',                       as: 'reduce'
    post 'adc_subscribed',                                             to: 'profiles#adc_subscribed',               as: 'adc_subscribed'
    

    get 'clientes/pendentes',                                         to: 'profiles#profiles_pending',              as: 'profiles_pending'
    get 'clientes/activos',                                           to: 'profiles#profiles_active',               as: 'profiles_active'
    get 'clientes/rejeitados',                                        to: 'profiles#profiles_rejecteds',            as: 'profiles_rejecteds'
    get 'clientes/bloqueados',                                        to: 'profiles#profiles_blockeds',             as: 'profiles_blockeds'
    
    
    get 'companies/details/:id',                                      to: 'companies#details',                    as: 'comapnies_details'
    get 'company/show_and_hidden_in_site/:id',                        to: 'companies#show_and_hidden_in_site',    as: 'show_and_hidden_in_site'
    get 'company/associate_user_company/:id',                         to: 'companies#associate_user_company',    as: 'associate_user_company'
    get 'company/reset-password/:id',                                 to: 'companies#reset_password_company_user',    as: 'reset_password_company_user'
    
    
    resources :admins                                                 #only: [:edit, :update]
    get 'admins/details/:id',                                         to: 'admins#details',                       as: 'admins_details'
    
    
    resources :publicities
    get 'publicity/show_pub_on_client/:id',                           to: 'publicities#show_pub_on_client',       as: 'show_pub_on_client'
    
    
    resources :partners
    get 'partner/show_and_hide_partner/:id',                          to: 'partners#show_and_hide_partner',       as: 'show_and_hide_partner'
    
    resources :categories
    resources :banks
    resources :products
    resources :stores
    resources :occupation_areas

    resources :companies do
        resources :bank_accounts, module: :companies
    end

    resources :configurations, only: [:edit, :update, :show] do
        resources :bank_accounts, module: :configurations
    end

    resources :profiles do
        resources :bank_accounts, module: :profiles
    end

end

app/models/store.rb
class Store < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  
  belongs_to :company
  belongs_to :category
  
  has_many :products, dependent: :destroy
  has_many :pre_orders, dependent: :destroy
  has_many :facturas, dependent: :destroy


  def self.all_of_request
    stores = Store.all.map{|store| store.name}
    stores << "Outro"
  end


end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  
  before_action :set_store, only: [
    :show, 
    :edit, 
    :update, 
    :destroy, 
    :consult_request, 
    :add_product_to_list, 
    :details_of_current_order, 
    :remove_item_order, 
    :validate_cart, 
    :validate_code_and_finish,
    :invoice_details
  ]
  before_action :set_pre_order, only: [ 
    :add_product_to_list, 
    :details_of_current_order, 
    :remove_item_order, 
    :validate_cart, 
    :validate_code_and_finish 
  ]
  before_action :set_item_order, only: [ :remove_item_order ]
  before_action :set_factura, only: [ :invoice_details ]

  load_and_authorize_resource
  
  # GET /stores
  # GET /stores.json
  def index
    @store = Store.new(company_id: current_user.company_id)

    @stores = current_user.company.stores
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @product = Product.new(store_id: @store.id)
  end

  def details_of_current_order
    
  end


  def consult_request   
    search = params["search"]
    user = User.find_by(cell_phone: search["cell_phone"]) if params["search"].present?
    
    if user.present?
        @pre_order = PreOrder.create(profile_id: user.profile.id, store_id: @store.id)
        redirect_to details_of_current_order_path(pre_order_id: @pre_order.id)
    else
        redirect_to @store, alert: 'Cliente não encontrado'
    end
  end

  def validate_cart
    @pre_order.profile.user.create_code_validation
  end

  def invoice_details
    
  end


  def validate_code_and_finish
    validation_code = params["validation_code"]

    if validation_code["code"].present?
        purchase_code = @pre_order.profile.user.purchase_codes.where(is_active: true).where(code: validation_code["code"]).first

        if purchase_code
            purchase_code.finish
            @pre_order.create_invoice(current_user)
            redirect_to @store, notice: 'Compra realizada com sucesso'
        else
            redirect_to validate_cart_path(pre_order_id: @pre_order.id), notice: 'Código não valido'
        end
    else
        redirect_to validate_cart_path(pre_order_id: @pre_order.id), alert: 'Código não valido'
    end

  end


  def add_product_to_list
    search = params["search"]
    product = nil

    if search["product_id"].present?
      product = Product.find(search["product_id"])
    else
      redirect_to details_of_current_order_path(pre_order_id: @pre_order.id), alert: 'Produto não encontrado'
    end


    if product.present?
      if (@pre_order.profile.purchase_amount >= product.first_parcel) # && (@pre_order.total_to_pay + product.price_with_commission) <= @pre_order.profile.purchase_amount)
          ItemOrder.create(product_id: product.id, pre_order_id: @pre_order.id)
          redirect_to details_of_current_order_path(pre_order_id: @pre_order.id), notice: 'Produto adicionado com sucesso'
      else
        redirect_to details_of_current_order_path(pre_order_id: @pre_order.id), alert: 'Valor do cliente não é suficiente para completar a compra'
      end

    end
  end




  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Loja registada com sucesso.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Loja atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_path, notice: 'Loja eliminada com sucesso.' }
      format.json { head :no_content }
    end
  end

  def remove_item_order
    @item_order.destroy

    redirect_to details_of_current_order_path(pre_order_id: @pre_order.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.friendly.find(params[:id])
    end

    def set_factura
      @factura = Factura.friendly.find(params[:factura_id])
    end

    def set_pre_order
      @pre_order = PreOrder.find(params[:pre_order_id])
    end

    def set_item_order
      @item_order = ItemOrder.find(params[:item_order_id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:name, :reference_number, :description, :location, :company_id, :category_id)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_details.html.erb
<div class="row">

    <div class="col-md-8">
        <!-- Products -->
        <div class="block">
            <div class="row">

                <% @store.products.each do |product| %>
                    <div class="col-lg-4">
                        <div class="card card-flex">
                            <div class="img-resize">
                                <% if product.image.attached? %>
                                    <%= image_tag(product.image, class: "card-img-top flex-img") %>
                                <% else %>
                                    <i class="fa fa-store fa-2x text-white"></i>
                                <% end %>
                            </div>

                            <div class="card-body">
                                <div class="m-2">
                                    <h5 class="card-title"><%= product.name %></h5>
                                    <p class="card-text mb-0"><b>Preço: </b><%= product.real_price.to_kwanza %></p>
                                    <p class="card-text mb-0"><b>Preço + Paga3: </b><%= product.price_with_commission.to_kwanza %></p>
                                </div>
                                <a href="<%= product_path(product) %>" class="btn btn-p3 btn-block btn-line">ver Detalhes</a>
                            </div>

                        </div>
                    </div>
                <% end %>

            </div>
        </div>
    </div>

    <div class="col-md-4">
        <!-- Updates -->
        <ul class="timeline timeline-alt py-0">
            <li class="timeline-event">
                <div class="timeline-event-icon bg-p3">
                    <i class="fa fa-briefcase"></i>
                </div>
                <div class="timeline-event-block block invisible" data-toggle="appear">
                    <div class="block-header">
                        <h3 class="block-title">Detalhes da loja</h3>
                    </div>
                    <div class="block-content block-content-full">
                        <p class="font-w600 mb-0">Nome da loja:</p>
                        <p class="font-size-sm mb-2"><%= @store.name %></p>

                        <p class="font-w600 mb-0">Categoria:</p>
                        <p class="font-size-sm mb-2"><%= @store&.category&.name %></p>

                        <p class="font-w600 mb-0">Referência:</p>
                        <p class="font-size-sm mb-2"><%= @store.reference_number %></p>

                        <p class="font-w600 mb-0">Localização:</p>
                        <p class="font-size-sm mb-2"><%= @store.location %></p>

                        <p class="font-w600 mb-0">Descrição:</p>
                        <p class="font-size-sm mb-2"><%= @store.description %></p>

                    </div>
                </div>
            </li>

        </ul>
        <!-- END Updates -->
    </div>

</div>

app/views/stores/_form_add_product.html.erb
<%= simple_form_for :search, url: add_product_to_list_path(pre_order_id: pre_order.id), method: "POST", html: { class: 'mb-4' } do |f| %>
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <%= f.input :product_id, 
                    :as => :select, :collection => @store.products.map { |product| ["#{product.name} - #{product.price_with_commission.to_kwanza}", product.id] }, 
                    input_html: { class: 'js-select2' },
                    label: false, 
                    placeholder: "Selecione o produto.." 
                %>
            </div>
        </div>
        
        <div class="col-md-4">
            <button type="submit" class="btn btn-p3 btn-sm">Adicionar</button>
        </div>
    </div>
<% end %>

app/views/stores/_form_purchase.html.erb
<%= simple_form_for :search, url: consult_request_path, method: "GET", html: { } do |f| %>
    <div class="modal fade main-modal-p3" id="modal-do-purchases" tabindex="-1" role="dialog" aria-labelledby="modal-block-large" aria-hidden="true">

        <div class="modal-dialog modal-dialog-popin" role="document">
            <div class="modal-content">
                <div class="block block-themed block-transparent mb-0">
                    <div class="block-header bg-primary-dark">
                        <h3 class="block-title">Processo de compra - Consultar</h3>

                        <div class="block-options">
                            <button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close"><i class="fa fa-fw fa-times"></i></button>
                        </div>
                    </div>

                    <div class="block-content font-size-md">
                        <div class="row">
                            <div class="col-12">
                                <%= f.input :cell_phone, label: "Nº telefone do cliente", placeholder: 'ex: 912090909' %>
                            </div>
                        </div>

                        <p class="parch-text"><em>Porfavor preencher os campos correctamente</em></p>
                    </div>

                    <br>

                    <div class="block-content block-content-full text-right border-top">
                        <button type="button" class="btn btn-sm btn-danger btn-sm" data-dismiss="modal">Cancelar</button>
                        <button type="submit" class="ml-2 btn btn-p3 button btn-sm"> <i class="fa fa-check mr-1"></i>Consultar </button>
                    </div>

                </div>
            </div>
        </div>

    </div>

<% end %>

app/views/stores/_purchases_list.html.erb
<div class="block">

    <div class="block-content">
        <table class="table table-vcenter">
          
            <thead>
                <tr>
                    <th>Cliente</th>
                    <th>Total</th>
                    <th class="d-none d-sm-table-cell" style="width: 15%;">Data</th>
                    <th class="text-center" style="width: 100px;">Acão</th>
                </tr>
            </thead>

            <tbody>
                <% @store.facturas.each do |factura| %>
                    <tr>
                        <th class="" scope="row"> <%= factura.user.profile.name %> </th>
                        <td class="font-w600 font-size-sm"> <%= link_to factura.total_pagar.to_kwanza, invoice_details_path( factura_id: factura ) %> </td>
                        <td class="d-none d-sm-table-cell"> <%= link_to factura.created_at.strftime("%d/%m/%Y"), invoice_details_path( factura_id: factura ) %> </td>
                        <td class="text-center">
                            <div class="btn-group">
                                <%= link_to invoice_details_path( factura_id: factura ), class: "btn btn-sm btn-light js-tooltip-enabled", "data-toggle": "tooltip", title: "", "data-original-title": "Ver detalhes" do %>
                                    <i class="fa fa-fw fa-eye"></i>
                                <% end %>
                            </div>
                        </td>
                    </tr>
                <% end %>
            </tbody>

        </table>
    </div>
</div>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<!-- Hero -->
<div class="bg-image overflow-hidden" style="background-image: url('/home.svg');">
    <div class="bg-primary-dark-op">
        <div class="content content-narrow content-full">
            <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center mt-5 mb-2 text-center text-sm-left">
                <div class="flex-sm-fill">
                    <h1 class="font-w600 text-white mb-0 invisible" data-toggle="appear">Lojas</h1>
                    <h2 class="h4 font-w400 text-white-75 mb-0 invisible" data-toggle="appear" data-timeout="250">Menu das lojas</h2>
                </div>
                <div class="flex-sm-00-auto mt-3 mt-sm-0 ml-sm-3">
                    <span class="d-inline-block invisible" data-toggle="appear" data-timeout="350">
                        <button type="button" class="btn btn-sm btn-p3 px-4 py-2" data-toggle="modal" data-target="#modal-create-store">
                            <i class="fa fa-plus mr-1"></i> Nova loja
                        </button>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Hero -->


<div class="content content-narrow">

    <div class="row row-deck">
        <div class="col-lg-12">
            <div class="block block-mode-loading-oneui">
                <div class="block-header border-bottom">
                    <h3 class="block-title">Lista das loja registadas</h3>
                    <div class="block-options">
                        <button type="button" class="btn-block-option" data-toggle="block-option" data-action="state_toggle" data-action-mode="demo">
                            <i class="si si-refresh"></i>
                        </button>
                        <button type="button" class="btn-block-option">
                            <i class="si si-settings"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="row" style="background: whitesmoke;">
        <% @stores.each do |store| %>

            <div class="col-lg-3 m1 mb-5">
                <div class="block-content " style="background-color: #ffffff;">
                    <div class="media d-flex align-items-center push">
                        
                        <div class="mr-3">
                            <%= link_to store_path(store), class: "item item-rounded bg-p3" do %>
                                <i class="fa fa-store fa-2x text-white-75"></i>
                            <% end %>
                        </div>

                        <div class="media-body">
                            <div class="font-w600"> <%= link_to store.name, store %> </div>
                            <div class="font-size-sm"> <%= link_to store.reference_number, store %> </div>
                        </div>

                        <%= link_to store, class: "btn btn-sm btn-danger align-stash-btn", method: :delete, data: { confirm: 'Tens certeza ?' } do %>
                            <i class="fas fa-times"></i>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>

    </div>



</div>

<%= render 'stores/form' %>

app/views/stores/invoice_details.html.erb
<!-- Hero -->
<div class="bg-image overflow-hidden" style="background-image: url('/home.svg');">
    <div class="bg-primary-dark-op">
        <div class="content content-narrow content-full">
            <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center mt-5 mb-2 text-center text-sm-left">
                <div class="flex-sm-fill">
                    <%= link_to @store, class: "link-fx font-size-h3 text-white", "data-toggle": "tooltip", title: "", "data-original-title": "Voltar na loja" do %>
                        <i class="fa fa-fw fa-eye"></i> Voltar na loja
                    <% end %>
                </div>
                <div class="flex-sm-00-auto mt-3 mt-sm-0 ml-sm-3">
                    <span class="d-inline-block invisible" data-toggle="appear" data-timeout="350">

                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Hero -->


<!-- Page Content -->
<div class="content content-boxed">
    <div class="row">
        <div class="col-md-9">
            <!-- Invoice -->
            <div class="block">
                <div class="block-header">
                    <h3 class="block-title"><%= @factura.reference %></h3>
                    
                    <button type="button" class="btn btn-sm btn-p3"  onclick="One.helpers('print');">
                        <i class="fa fa-print mr-1"></i> Imprimir factura
                    </button>
                </div>
                
                <div class="block-content">
                    <div class="">
                        <h1>Carregar a ficha técnica</h1>
                        <!-- <iframe src="<%# adc_details_url(@factura.adc, format: "pdf")%>" width="100%" height="500px" class=""></iframe> -->
                    </div>
                </div>
            </div>
            <!-- END Invoice -->        
        </div>

        <div class="col-md-3">
            <!-- Invoice -->
            <div class="block">
                <div class="block-header">
                    <h3 class="block-title">Recibos</h3>
                    <hr>
                </div>
                <div class="block-content">

                    <% @factura.receipts.each do |recibo| %>
                        <%= link_to root_path, class: "js-swal-success btn btn-light push", target: "_blank" do %>
                            <i class="fa fa-check-circle text-success mr-1"></i> Recibo de - <%= recibo.created_at.strftime("%d/%m/%Y")%>
                        <% end %>       
                    <% end %>       

                </div>
            </div>
            <!-- END Invoice -->  
        </div>
    </div>

</div>
<!-- END Page Content -->

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

app/views/stores/validate_cart.html.erb
<!-- Hero -->
<div class="bg-image overflow-hidden" style="background-image: url('/home.svg');">
    <div class="bg-primary-dark-op">
        <div class="content content-narrow content-full">
            <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center mt-5 mb-2 text-center text-sm-left">
                <div class="flex-sm-fill">
                    <%= link_to @store, class: "link-fx font-size-h3 text-white", "data-toggle": "tooltip", title: "", "data-original-title": "Ver detalhes" do %>
                        <i class="fa fa-fw fa-trash"></i> Cancelar compra
                    <% end %>
                </div>
                <div class="flex-sm-00-auto mt-3 mt-sm-0 ml-sm-3">
                    <h1 class="font-w600 text-white mb-0 invisible" data-toggle="appear"><%= "Processo de validação da venda" %></h1>
                    <h2 class="h4 font-w400 text-white-75 mb-0 invisible" data-toggle="appear" data-timeout="250"><%= DateTime.now.strftime("%d/%m/%Y - %H:%M") %></h2>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Hero -->


<!-- Page Content -->
<div class="content content-boxed">


    <div class="row justify-content-md-center">

        <%= simple_form_for :validation_code, url: validate_code_and_finish_path, method: "POST", html: { class: 'form-inline mb-3' } do |f| %>
            <div class="form-group mx-sm-3 mb-2">
                <input type="text" class="form-control" placeholder="código de validação" pattern="[0-9]{4}" maxlength="4" name="validation_code[code]" id="validation_code_code">
            </div>
            <button type="submit" class="btn btn-primary mb-2">Confirmar</button>
        <% end %>



    </div>


    <div class="row justify-content-md-center">
        <div class="col-md-10">
            <!-- Updates -->
            <ul class="timeline timeline-alt py-0">
                <li class="timeline-event">
                    <div class="timeline-event-icon bg-p3">
                        <i class="fa fa-briefcase"></i>
                    </div>
                    <div class="timeline-event-block block invisible" data-toggle="appear">
                        <div class="block-header">
                            <h3 class="block-title">Detalhes</h3>
                        </div>
                        
                        <div class="block-content">
                            <div class="row">
                                <div class="col-6">
                                    <div class="font-size-sm font-w600 text-muted text-uppercase">Total das compras</div>
                                    <a class="link-fx font-size-h3" href="javascript:void(0)"><%= @pre_order.total_to_pay.to_kwanza %></a>
                                </div>

                                <div class="col-6 text-right ">
                                    <div class="font-size-sm font-w600 text-muted text-uppercase">Primeira Parcela</div>
                                    <a class="link-fx font-size-h3" href="javascript:void(0)"><%= @pre_order.first_instalment.to_kwanza %></a>
                                </div>
                            </div>

                            <hr>
                            <p><span class="font-w600 mb-2">Nome: </span><span class="font-size-sm"><%= @pre_order.profile.name %></span></p>
                            <p><span class="font-w600 mb-2">Nº de telefone: </span><span class="font-size-sm"><%= @pre_order.profile.user.cell_phone %></span></p>
                            <p><span class="font-w600 mb-2">E-mail: </span><span class="font-size-sm"><%= @pre_order.profile.user.email %></span></p>
                            <p><span class="font-w600 mb-2">Endereço: </span><span class="font-size-sm"><%= @pre_order.profile.address %></span></p>
                            <p><span class="font-w600 mb-2">Nº Bilhete de identidade: </span><span class="font-size-sm"><%= @pre_order&.profile&.bi %></span></p>
                            <hr>
                            <p><span class="font-w600 mb-2">Entidade empregadora: </span><span class="font-size-sm"><%= @pre_order&.profile&.company_name %></span></p>
                            <p><span class="font-w600 mb-2">Função: </span><span class="font-size-sm"><%= @pre_order&.profile&.position %></span></p>
                            
                        </div>
                    </div>
                </li>

            </ul>
            <!-- END Updates -->
        </div>
        
    </div>
</div>
<!-- END Page Content -->

 