config/routes.rb
Rails.application.routes.draw do
    resources :requests
    resources :moviments
    resources :messages


    get '/minhas-solicitacoes',                                       to: 'requests#my_requests',                 as: 'my_requests'
    get '/cancelar-solicitacao/:id',                                  to: 'requests#cancel_my_request',           as: 'cancel_my_request'
    put '/aprovar-solicitacao/:id',                                   to: 'requests#approve_request',             as: 'approve_request'
    put '/confirmacao-da-solicitacao/:id',                            to: 'requests#confirmation_request',        as: 'confirmation_request'

    


    root 'site#index'
    get '/empresas',                                                  to: 'site#empresas',                        as: 'empresas'
    get '/produtos_disponiveis/:id',                                  to: 'site#available_products',              as: 'available_products'
    
    #get '/termos-e-condicoes',                                        to: 'site#terms_and_conditios',             as: 'terms_and_conditios'
    
    devise_for :users, controllers: {
        sessions: 'users/sessions'
    }
    
    resources :users, only: [:index, :show, :new, :edit]
    get 'users/active_and_inactive_user/:id',                         to: 'users#active_and_inactive_user',       as: 'active_and_inactive_user'
    get 'users/active_and_inactive_profile/:id',                      to: 'users#active_and_inactive_profile',    as: 'active_and_inactive_profile'
    get 'users/aprove_profile/:id',                                   to: 'users#aprove_profile',                  as: 'aprove_profile'
    
    
    
    
    
    get '/pagamentos',                                                to: 'invoices#index',                       as: 'invoices'
    get '/vendas',                                                    to: 'invoices#sales',                       as: 'sales'
    get '/minhas_compras',                                            to: 'invoices#purchases',                   as: 'purchases'
    get '/recibo/:id',                                                to: 'invoices#recibo',                      as: 'recibo'
    get '/adc_details/:id',                                           to: 'invoices#adc_details',                 as: 'adc_details'
    
    
    
    get '/stores/:id/validate_cart/:pre_order_id',                    to: 'stores#validate_cart',                 as: 'validate_cart'
    post '/stores/:id/validate_code_and_finish/:pre_order_id',        to: 'stores#validate_code_and_finish',       as: 'validate_code_and_finish'
    get '/stores/:id/invoice_details/:factura_id',                    to: 'stores#invoice_details',               as: 'invoice_details'
    
    get '/detalhes_da_venda/:factura_id',                             to: 'invoices#details',                     as: 'details'
    get '/detalhes_da_compra/:factura_id',                            to: 'invoices#details_purchase',            as: 'details_purchase'
    get '/detalhes_da_factura/:factura_id',                           to: 'invoices#show',                        as: 'details_invoice'
    
    get '/stores/:id/remove_item_order/:item_order_id',               to: 'stores#remove_item_order',             as: 'remove_item_order'
    get '/stores/:id/consult_request',                                to: 'stores#consult_request',               as: 'consult_request'
    post '/stores/:id/add_product_to_list/:pre_order_id',             to: 'stores#add_product_to_list',           as: 'add_product_to_list'
    get '/stores/:id/details_of_current_order/:pre_order_id',         to: 'stores#details_of_current_order',      as: 'details_of_current_order'
    
    get '/dashboard',                                                 to: 'dashboard#index',                      as: 'dashboard'
    get '/validate_cell_phone_number',                                to: 'dashboard#validate_cell_phone_number', as: 'validate_cell_phone_number'
    

    get 'profiles/validate_profile/:id',                               to: 'profiles#validate_profile',             as: 'validate_profile'
    get 'profiles/rejected_profile/:id',                               to: 'profiles#rejected_profile',             as: 'rejected_profile'
    get 'profiles/details/:id',                                        to: 'profiles#details',                      as: 'profiles_details'
    get 'profiles/active_edit/:id',                                    to: 'profiles#active_edit',                  as: 'active_edit'
    get 'profiles/unlock_account/:id',                                 to: 'profiles#unlock_account',               as: 'unlock_account'
    put 'profiles/:id',                                                to: 'profiles#reduce',                       as: 'reduce'
    post 'adc_subscribed',                                             to: 'profiles#adc_subscribed',               as: 'adc_subscribed'
    

    get 'clientes/pendentes',                                         to: 'profiles#profiles_pending',              as: 'profiles_pending'
    get 'clientes/activos',                                           to: 'profiles#profiles_active',               as: 'profiles_active'
    get 'clientes/rejeitados',                                        to: 'profiles#profiles_rejecteds',            as: 'profiles_rejecteds'
    get 'clientes/bloqueados',                                        to: 'profiles#profiles_blockeds',             as: 'profiles_blockeds'
    
    
    get 'companies/details/:id',                                      to: 'companies#details',                    as: 'comapnies_details'
    get 'company/show_and_hidden_in_site/:id',                        to: 'companies#show_and_hidden_in_site',    as: 'show_and_hidden_in_site'
    get 'company/associate_user_company/:id',                         to: 'companies#associate_user_company',    as: 'associate_user_company'
    get 'company/reset-password/:id',                                 to: 'companies#reset_password_company_user',    as: 'reset_password_company_user'
    
    
    resources :admins                                                 #only: [:edit, :update]
    get 'admins/details/:id',                                         to: 'admins#details',                       as: 'admins_details'
    
    
    resources :publicities
    get 'publicity/show_pub_on_client/:id',                           to: 'publicities#show_pub_on_client',       as: 'show_pub_on_client'
    
    
    resources :partners
    get 'partner/show_and_hide_partner/:id',                          to: 'partners#show_and_hide_partner',       as: 'show_and_hide_partner'
    
    resources :categories
    resources :banks
    resources :products
    resources :stores
    resources :occupation_areas

    resources :companies do
        resources :bank_accounts, module: :companies
    end

    resources :configurations, only: [:edit, :update, :show] do
        resources :bank_accounts, module: :configurations
    end

    resources :profiles do
        resources :bank_accounts, module: :profiles
    end

end

app/models/company.rb
class Company < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged
    
    belongs_to                      :user, optional: true
    belongs_to                      :category
    has_many :stores,               dependent: :destroy
    has_many :products,             through: :stores
    has_many :bank_accounts,        as: :accountble, dependent: :destroy
    has_many :facturas,             through: :stores
    has_many :recibos,              through: :facturas

    has_one_attached    :avatar

    validates :name, presence: {message: 'Não pode estar em branco'}
    validates :nif, presence: {message: 'Não pode estar em branco'}
    validates :address, presence: {message: 'Não pode estar em branco'}
    validates :email, 
        presence: true, 
        length: { maximum: 250 }, 
        uniqueness: {
            case_sensitive: false, 
            scope: :user_id
        }
        #format: { with: URI::MailTo::EMAIL_REGEXP } 
        #format: {
        #    with: EMAIL_REGEX,
        #    message: "caracteres inválidos. Ex: utilizador@email.co"
        #}

    validates :accountNumber, 
        :numericality => {
            :only_integer => true, 
            message: "Número de conta inválido"
        },
        presence: true, 
        uniqueness: { case_sensitive: false, scope: :user_id }

    validates :iban, 
        presence: {message: "Não pode estar em branco!"}, 
        uniqueness: { case_sensitive: false, scope: :user_id }

    validates :cell_phone, 
        presence: {message: "Não pode estar em branco!"},
        length: { maximum: 250 }, 
        uniqueness: { 
            case_sensitive: false, 
            scope: :user_id 
        },
        :numericality => {
            :only_integer => true, 
            message: "Número de telefone inválido"
        },
        length: {
            in: 9..9, 
            message: "Número de telefone inválido. Ex: 923456699"
        }

    #validate :validar_cell_phone, :validar_email, on: :create

    def self.search(search)
        where(
            "lower(name) LIKE ? OR 
            lower(cell_phone) LIKE ? OR
            lower(email) LIKE ?", 
            "%#{search.downcase}%", 
            "%#{search.downcase}%",
            "%#{search.downcase}%"
        )
    end


    def validar_email
        if User.find_by(email: self.email)
            errors.add(:email, 'E-mail indisponível')
        end
    end

    def validar_cell_phone
        if User.find_by(cell_phone: self.cell_phone)
            errors.add(:cell_phone, 'Número de telemóvel indisponível')
        end
    end

    def reset_password
        user = self.user
        pw = rand(2**256).to_s(36).ljust(8, 'a')[0..10]

        user.password = pw
        user.password_confirmation = pw
        user.full_name = self.name
        user.save!
        msg = "Redefinição de Senha - Paga3\nUtilizador: #{user.email}\nSenha: #{pw}"
        SendSMS.new( msg, user.cell_phone).call
    end


    def create_access_user 
        
        old_user = nil
        pw = rand(2**256).to_s(36).ljust(8, 'a')[0..10]

        if self.user_id.present? #==================== Usuário existe mas não esta associado
            old_user = get_user_by_id(self.user_id)
            update_info_user(self, old_user, pw)
        else #==================== Usuário não existe, Busca pelo e-mail se existe um
            #old_user = get_user_by_email(self.email)
            user = User.create(
                full_name: self.name,
                email: self.email, 
                cell_phone: self.cell_phone, 
                confirmation_terms: true, 
                role: 1,
                identity_number: self.nif,
                password: pw, 
                password_confirmation: pw
            )
    
            self.update_columns(user_id: user.id)
            content = "<h4>Seja bem-vindo à Paga3</h4><p><strong>Utilizador</strong>: #{user.email}</p><p><strong>senha</strong>: #{pw}</p>"
            SendMailer.new(user.email, "BEM VINDO", content ).call
            user.notification_new_user(pw)
            welcome_notification(user)
        end
    end

    def update_info_user(comapny, user, pw)
        comapny.update_columns(user_id: user.id)

        user.full_name = self.name
        user.password = pw
        user.password_confirmation = pw
        user.save

        user.notification_new_user(pw)
        welcome_notification(user)
    end

    def get_user_by_id(user_id)
        return User.find(user_id)
    end

    def get_user_by_email(email)
        return User.find_by(email: email)
    end

    def welcome_notification(user)
        msg = "Olá #{self.name},\nSeja bem-vindo à Paga3, por favor registe as suas lojas e produtos para estar visível em nossa plataforma." 
        SendSMS.new( msg, user.cell_phone ).call
    end

    def show_and_hidden_in_site
        if self.show_in_site
            self.update_columns(show_in_site: false)
        else
            self.update_columns(show_in_site: true)
        end
        
    end

end

app/controllers/companies/bank_accounts_controller.rb
class Companies::BankAccountsController < BankAccountsController
    before_action :set_accountble

    def create
        # NOTIFY
        super
    end
    
    private
        def set_accountble
            @accountble = Company.friendly.find(params[:company_id])

        end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
        
    before_action :set_comapny, only: [
        :details, 
        :edit, 
        :update, 
        :show, 
        :destroy, 
        :show_and_hidden_in_site, 
        :associate_user_company,
        :reset_password_company_user
    ]
    
    load_and_authorize_resource
    
    def index
        if params[:search]
            @pagy, @companies = pagy(Company.search(params[:search]).where.not(name: nil).order('created_at DESC'), items: 10)
        else
            @pagy, @companies = pagy(Company.where.not(name: nil).order('created_at DESC'), items: 10)
        end
    end

    def edit
    end

    def reset_password_company_user
        if @company.user.present?
            @company.reset_password
            redirect_to @company, notice: 'Nova senha enviada com sucesso.'          
        else
            redirect_to @company, alert: 'Lamentamos mas não há utilizador associado a esta empresa.'
        end
    end

    def show
    end

    def new
        @company = Company.new
    end

    def associate_user_company
        @company.create_access_user
        redirect_to @company, notice: 'Mensagem enviada com sucesso.'
    end

    def show_and_hidden_in_site
        @company.show_and_hidden_in_site
        redirect_to @company, notice: 'Informação da Empresa actualizada no site.'
    end

    def create
        @company = Company.new(company_params_new)

        respond_to do |format|
            if @company.save
                @company.create_access_user
                format.html { redirect_to @company, notice: 'Empresa registada com sucesso.' }
                format.json { render :show, status: :created, location: @company }
            else
                format.html { render :new }
                format.json { render json: @company.errors.messages, status: :unprocessable_entity }
            end
        end
    end


    def update
        respond_to do |format|
            #@company.email = @company.user.email
            #@company.create_access_user

            if @company.update(company_params)
                format.html { redirect_to company_path(@company), notice: 'Empresa atualizada com sucesso.' }
                format.json { render :show, status: :ok, location: @company }
            else
                p @company.errors.messages
                format.html { render :edit }
                format.json { render json: @company.errors, status: :unprocessable_entity }
            end
        end
    end


    def details
    end

    def destroy
        user =  @company.user

        if user.is_active?
            user.inactive_user
        else
            user.active_user
        end

        if @company.present?
            @company.destroy
            user.delete if user.present?
        end


        respond_to do |format|
            format.html { redirect_to companies_path, notice: 'Empresa eliminada com sucesso.' }
            format.json { head :no_content }
        end
    end

    private
        def set_comapny
            @company = Company.friendly.find(params[:id])
        end

        def company_params
            params.require(:company).permit(
                :avatar, :name, :nif, :address, :cell_phone, :category_id,
                :accountNumber, :iban, :user_id
            )
        end

        def company_params_new
            params.require(:company).permit(
                :avatar, :name, :nif, :address, :cell_phone, :email, :category_id,
                :accountNumber, :iban, :user_id
            )
        end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/details.html.erb
<!-- Hero -->
<div class="bg-image" style="background-image: url('/home.svg');">
    <div class="bg-black-50">
        <div class="content content-full text-center">
            <div class="my-3">
                <% if @company.avatar.attached? %>
                    <%= image_tag(@company.avatar, class: "img-avatar img-avatar-thumb") %>
                <% else %>
                    <img class="img-avatar img-avatar-thumb" src="/templete/assets/media/avatars/avatar13.jpg" alt="">
                <% end %>
            </div>
            <h1 class="h2 text-white mb-0"><%= @company.name %></h1>
            <span class="text-white-75"><%= @company.cell_phone %></span>
        </div>
    </div>
</div>
<!-- END Hero -->


<!-- Stats -->
<div class="bg-white border-bottom">
    <div class="content content-boxed">
        <div class="row items-push text-center">
            <div class="col-6 col-md-2">
                <div class="font-size-sm font-w600 text-muted text-uppercase">Compensação</div>
                <a class="link-fx font-size-h3" href="javascript:void(0)"><%= 0.to_kwanza %></a>
            </div>
            <div class="col-6 col-md-2">
                <div class="font-size-sm font-w600 text-muted text-uppercase">Quant. Lojas</div>
                <a class="link-fx font-size-h3" href="javascript:void(0)"><%= @company.stores.count %></a>
            </div>
            <div class="col-6 col-md-2">
                <div class="font-size-sm font-w600 text-muted text-uppercase">Quant. Produtos</div>
                <a class="link-fx font-size-h3" href="javascript:void(0)"><%= @company.products.count %></a>
            </div>
      
            <div class="col-6 col-md-6">
            <div class="col-6 col-md-6 float-right">
                <button type="button" class="btn btn-sm btn-primary" data-toggle="modal" data-target="#modal-form_bankble">
                    <i class="fa fa-plus mr-1"></i> Adicionar banco
                </button>
                
                <%= link_to edit_company_path(@company), class: "btn btn-sm btn-success" do %>
                    <span class="fa fa-edit"></span> actualizar
                <% end %>
            </div>
        </div>
    </div>
</div>

<!-- Page Content -->
<div class="content content-boxed">
    <div class="row">
        <div class="col-md-7 col-xl-8">
            <!-- Updates -->
            <ul class="timeline timeline-alt py-0">
                <li class="timeline-event">
                    <div class="timeline-event-icon bg-p3">
                        <i class="fa fa-briefcase"></i>
                    </div>
                    <div class="timeline-event-block block invisible" data-toggle="appear">
                        <div class="block-header">
                            <h3 class="block-title">Informações do perfil</h3>
                        </div>
                        
                        <div class="block-content">
                            <p><span class="font-w600 mb-2">Nome: </span><span class="font-size-sm"><%= @company.name %></span></p>
                            <p><span class="font-w600 mb-2">E-mail: </span><span class="font-size-sm"><%= @company&.user.email %></span></p>
                            <p><span class="font-w600 mb-2">Nº de telefone: </span><span class="font-size-sm"><%= @company.cell_phone %></span></p>
                            <p><span class="font-w600 mb-2">Endereço: </span><span class="font-size-sm"><%= @company.address %></span></p>
                            <p><span class="font-w600 mb-2">NIF: </span><span class="font-size-sm"><%= @company.nif %></span></p>
                            <p><span class="font-w600 mb-2">Nº Conta: </span><span class="font-size-sm"><%= @company.accountNumber %></span></p>
                            <p><span class="font-w600 mb-2">IBAN: </span><span class="font-size-sm"><%= @company.iban %></span></p>
                            <p><span class="font-w600 mb-2">Endereço: </span><span class="font-size-sm"><%= @company.address %></span></p>
                        </div>
                    </div>
                </li>

            </ul>
            <!-- END Updates -->
        </div>
        <div class="col-md-5 col-xl-4">
            <%= render 'bank_accounts/bank_accounts', accountble: @company %>

        </div>
    </div>
</div>
<!-- END Page Content -->

<%= render 'bank_accounts/form', accountble: @company %>

app/views/companies/edit.html.erb
<!-- Hero -->
<div class="bg-image" style="background-image: url('/home.svg');">
    <div class="bg-black-50">
        <div class="content content-full text-center">
            <div class="my-3">
                <% if @company.avatar.attached? %>
                    <%= image_tag(@company.avatar, class: "img-avatar img-avatar-thumb") %>
                <% else %>
                    <img class="img-avatar img-avatar-thumb" src="/templete/assets/media/avatars/avatar13.jpg" alt="">
                <% end %>
            </div>
            <h1 class="h2 text-white mb-0"><%= @company.name %></h1>
            <span class="text-white-75"><%= @company.cell_phone %></span>
        </div>
    </div>
</div>
<!-- END Hero -->

<%= simple_form_for(@company) do |f| %>

    <div class="content content-boxed">
        <div class="row">
            <div class="col-md-12">
                <!-- Updates -->
                <ul class="timeline timeline-alt py-0">
                    <li class="timeline-event">
                        <div class="timeline-event-icon bg-p3">
                            <i class="fa fa-edit"></i>
                        </div>
                        <div class="timeline-event-block block invisible" data-toggle="appear">
                            <div class="block-header">
                                <h3 class="block-title">Actualizar Informações</h3>
                            </div>
                            
                            <div class="block-content">
                                <div class="row">
                                    <div class="col-md-6">
                                        <%= f.input :name, label: 'Nome da empresa' %>
                                        <%= f.input :email, label: 'E-mail' %>
                                        <%= f.input :cell_phone, label: 'Nº telefone' %>
                                        <%= f.input :address, label: 'Endereço' %>
                                        <br>
                                        <%= f.input :avatar, label: 'Logotipo da empresa' %>
                                    </div>
                                    <div class="col-md-6">
                                        <%= f.input :nif, label: 'NIF' %>
                                        <%= f.input :accountNumber, label: 'Nº de conta', error: 'Nº de conta não pode estar em branco' %>
                                        <%= f.input :iban, label: 'IBAN' %>
                                        <%= f.association :category, label: 'Categoria' %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>

                </ul>

                <div class="form-actions text-right">
                    <%= f.button :submit, "Actualizar", class: "btn btn-p3 btn-sm mr-2" %>
                    <%= link_to 'Cancelar', company_path(@company), class: 'btn btn-sm btn-danger' %>
                </div>
                <!-- END Updates -->
            </div>
        </div>
    </div>

<% end %>

app/views/companies/show.html.erb
<!-- Hero -->
<div class="bg-image" style="background-image: url('/home.svg');">
    <div class="bg-black-50">
        <div class="content content-full text-center">
            <div class="my-3">
                <% if @company.avatar.attached? %>
                <%= image_tag(@company.avatar, class: "img-avatar img-avatar-thumb") %>
                <% else %>
                <img class="img-avatar img-avatar-thumb" src="/templete/assets/media/avatars/avatar13.jpg" alt="">
                <% end %>
            </div>
            <h1 class="h2 text-white mb-0"><%= @company.name %></h1>
            <span class="text-white-75"><%= @company.cell_phone %></span>
        </div>
    </div>
</div>
<!-- END Hero -->


<!-- Stats -->
<div class="bg-white border-bottom">
    <div class="content content-boxed">
        <div class="row items-push text-center">
            <div class="col-6 col-md-2">
                <div class="font-size-sm font-w600 text-muted text-uppercase">Compensação</div>
                <a class="link-fx font-size-h3" href="javascript:void(0)"><%= 0.to_kwanza %></a>
            </div>
            <div class="col-6 col-md-2">
                <div class="font-size-sm font-w600 text-muted text-uppercase">Quant. Lojas</div>
                <a class="link-fx font-size-h3" href="javascript:void(0)"><%= @company.stores.count %></a>
            </div>
            <div class="col-6 col-md-2">
                <div class="font-size-sm font-w600 text-muted text-uppercase">Quant. Produtos</div>
                <a class="link-fx font-size-h3" href="javascript:void(0)"><%= @company.products.count %></a>
            </div>
            <div class="col-6 col-md-6 text-right">
                <div class="btn-group">
                    <button type="button" class="btn btn-p3 btn-p3 dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menu Opções</button>
                    <div class="dropdown-menu">
                        <%= link_to 'actualizar', edit_company_path(@company), class: "dropdown-item" %>
                        <% if current_user.admin? %>
                            <% if @company.user.present? %>
                                <% if @company.user.is_active %>
                                    <%= link_to 'Desactivar conta', active_and_inactive_user_path(@company.user), class: "dropdown-item", data: { confirm: 'Tens certeza ?' } %>
                                <% else %>
                                    <%= link_to 'Activar conta', active_and_inactive_user_path(@company.user), class: "dropdown-item", data: { confirm: 'Tens certeza ?' } %>
                                <% end %>

                                <% if @company.show_in_site %>
                                    <%= link_to 'Tirar do site', show_and_hidden_in_site_path(@company), class: "dropdown-item", data: { confirm: 'Tens certeza ?' } %>
                                <% else %>
                                    <%= link_to 'Mostrar no site', show_and_hidden_in_site_path(@company), class: "dropdown-item", data: { confirm: 'Tens certeza ?' } %>
                                <% end %>
                            <% else %>
                                <%= link_to 'Associar Utilizador', associate_user_company_path(@company), class: "dropdown-item", data: { confirm: "Esta acção vai associar um utilizador à esta empresa \nTens certeza ?" } %>
                            <% end %>
                        <% end %>

                        <div class="dropdown-divider"></div>
                        <%# link_to 'Resetar Senha', reset_password_company_user_path(@company), class: "dropdown-item", style: "background-color: #70b9eb; color: #fff; margin-bottom: 5px;", data: { confirm: "Esta acção enviará uma nova senha ao utilizador ?\nUtilizador: #{@company.name}" } %>
                        <%# link_to 'Eliminar empresa', company_path(@company), class: "dropdown-item", data: { confirm: 'Tens certeza ?', :method => :delete }, style: "background-color: #ff5722; color: #fff;" %>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<!-- Page Content -->
<div class="content content-boxed">
    <div class="row">
        <div class="col-md-9 col-sm-12">
            <!-- Updates -->
            <ul class="timeline timeline-alt py-0">
                <li class="timeline-event">
                    <div class="timeline-event-icon bg-p3">
                        <i class="fa fa-briefcase"></i>
                    </div>
                    <div class="timeline-event-block block invisible" data-toggle="appear">
                        <div class="block-header">
                            <h2 class="block-title">Detalhes da empresa</h2>
                        </div>

                        <div class="block-content">
                            <p><span class="font-w600 mb-2">Nome: </span><span class="font-size-sm"><%= @company.name %></span></p>
                            <p><span class="font-w600 mb-2">E-mail: </span><span class="font-size-sm"><%= @company.email %></span></p>
                            <p><span class="font-w600 mb-2">Nº de telefone: </span><span class="font-size-sm"><%= @company.cell_phone %></span></p>
                            <p><span class="font-w600 mb-2">Nº Conta: </span><span class="font-size-sm"><%= @company.accountNumber %></span></p>
                            <p><span class="font-w600 mb-2">IBAN: </span><span class="font-size-sm"><%= @company.iban %></span></p>
                            <p><span class="font-w600 mb-2">Endereço: </span><span class="font-size-sm"><%= @company.address %></span></p>
                            <p><span class="font-w600 mb-2">NIF: </span><span class="font-size-sm"><%= @company.nif %></span></p>
                            <p><span class="font-w600 mb-2">Categoria: </span><span class="font-size-sm"><%= @company&.category&.name %></span></p>
                        </div>
                    </div>
                </li>
            </ul>
            <!-- END Updates -->
        </div>

        <div class="col-md-3 col-sm-12">
            <div class="block">
                <div class="block-header block-header-default">
                    <h3 class="block-title">
                        <i class="fa fa-briefcase text-muted mr-1"></i> Historico de pagamentos
                    </h3>
                </div>
                <div class="block-content">
                    <% @company.recibos.each do |recibo| %>
                        <%= link_to recibo_path(recibo, format: "pdf"), class: "js-swal-success btn btn-light push", target: "_blank" do %>
                            <i class="si si-doc fa-2x text-success mr-1"></i>
                            <span class="mb-1">Recibo de - <%= recibo.created_at.strftime("%d/%m/%Y")%></span>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>