config/routes.rb
Rails.application.routes.draw do
    resources :requests
    resources :moviments
    resources :messages


    get '/minhas-solicitacoes',                                       to: 'requests#my_requests',                 as: 'my_requests'
    get '/cancelar-solicitacao/:id',                                  to: 'requests#cancel_my_request',           as: 'cancel_my_request'
    put '/aprovar-solicitacao/:id',                                   to: 'requests#approve_request',             as: 'approve_request'
    put '/confirmacao-da-solicitacao/:id',                            to: 'requests#confirmation_request',        as: 'confirmation_request'

    


    root 'site#index'
    get '/empresas',                                                  to: 'site#empresas',                        as: 'empresas'
    get '/produtos_disponiveis/:id',                                  to: 'site#available_products',              as: 'available_products'
    
    #get '/termos-e-condicoes',                                        to: 'site#terms_and_conditios',             as: 'terms_and_conditios'
    
    devise_for :users, controllers: {
        sessions: 'users/sessions'
    }
    
    resources :users, only: [:index, :show, :new, :edit]
    get 'users/active_and_inactive_user/:id',                         to: 'users#active_and_inactive_user',       as: 'active_and_inactive_user'
    get 'users/active_and_inactive_profile/:id',                      to: 'users#active_and_inactive_profile',    as: 'active_and_inactive_profile'
    get 'users/aprove_profile/:id',                                   to: 'users#aprove_profile',                  as: 'aprove_profile'
    
    
    
    
    
    get '/pagamentos',                                                to: 'invoices#index',                       as: 'invoices'
    get '/vendas',                                                    to: 'invoices#sales',                       as: 'sales'
    get '/minhas_compras',                                            to: 'invoices#purchases',                   as: 'purchases'
    get '/recibo/:id',                                                to: 'invoices#recibo',                      as: 'recibo'
    get '/adc_details/:id',                                           to: 'invoices#adc_details',                 as: 'adc_details'
    
    
    
    get '/stores/:id/validate_cart/:pre_order_id',                    to: 'stores#validate_cart',                 as: 'validate_cart'
    post '/stores/:id/validate_code_and_finish/:pre_order_id',        to: 'stores#validate_code_and_finish',       as: 'validate_code_and_finish'
    get '/stores/:id/invoice_details/:factura_id',                    to: 'stores#invoice_details',               as: 'invoice_details'
    
    get '/detalhes_da_venda/:factura_id',                             to: 'invoices#details',                     as: 'details'
    get '/detalhes_da_compra/:factura_id',                            to: 'invoices#details_purchase',            as: 'details_purchase'
    get '/detalhes_da_factura/:factura_id',                           to: 'invoices#show',                        as: 'details_invoice'
    
    get '/stores/:id/remove_item_order/:item_order_id',               to: 'stores#remove_item_order',             as: 'remove_item_order'
    get '/stores/:id/consult_request',                                to: 'stores#consult_request',               as: 'consult_request'
    post '/stores/:id/add_product_to_list/:pre_order_id',             to: 'stores#add_product_to_list',           as: 'add_product_to_list'
    get '/stores/:id/details_of_current_order/:pre_order_id',         to: 'stores#details_of_current_order',      as: 'details_of_current_order'
    
    get '/dashboard',                                                 to: 'dashboard#index',                      as: 'dashboard'
    get '/validate_cell_phone_number',                                to: 'dashboard#validate_cell_phone_number', as: 'validate_cell_phone_number'
    

    get 'profiles/validate_profile/:id',                               to: 'profiles#validate_profile',             as: 'validate_profile'
    get 'profiles/rejected_profile/:id',                               to: 'profiles#rejected_profile',             as: 'rejected_profile'
    get 'profiles/details/:id',                                        to: 'profiles#details',                      as: 'profiles_details'
    get 'profiles/active_edit/:id',                                    to: 'profiles#active_edit',                  as: 'active_edit'
    get 'profiles/unlock_account/:id',                                 to: 'profiles#unlock_account',               as: 'unlock_account'
    put 'profiles/:id',                                                to: 'profiles#reduce',                       as: 'reduce'
    post 'adc_subscribed',                                             to: 'profiles#adc_subscribed',               as: 'adc_subscribed'
    

    get 'clientes/pendentes',                                         to: 'profiles#profiles_pending',              as: 'profiles_pending'
    get 'clientes/activos',                                           to: 'profiles#profiles_active',               as: 'profiles_active'
    get 'clientes/rejeitados',                                        to: 'profiles#profiles_rejecteds',            as: 'profiles_rejecteds'
    get 'clientes/bloqueados',                                        to: 'profiles#profiles_blockeds',             as: 'profiles_blockeds'
    
    
    get 'companies/details/:id',                                      to: 'companies#details',                    as: 'comapnies_details'
    get 'company/show_and_hidden_in_site/:id',                        to: 'companies#show_and_hidden_in_site',    as: 'show_and_hidden_in_site'
    get 'company/associate_user_company/:id',                         to: 'companies#associate_user_company',    as: 'associate_user_company'
    get 'company/reset-password/:id',                                 to: 'companies#reset_password_company_user',    as: 'reset_password_company_user'
    
    
    resources :admins                                                 #only: [:edit, :update]
    get 'admins/details/:id',                                         to: 'admins#details',                       as: 'admins_details'
    
    
    resources :publicities
    get 'publicity/show_pub_on_client/:id',                           to: 'publicities#show_pub_on_client',       as: 'show_pub_on_client'
    
    
    resources :partners
    get 'partner/show_and_hide_partner/:id',                          to: 'partners#show_and_hide_partner',       as: 'show_and_hide_partner'
    
    resources :categories
    resources :banks
    resources :products
    resources :stores
    resources :occupation_areas

    resources :companies do
        resources :bank_accounts, module: :companies
    end

    resources :configurations, only: [:edit, :update, :show] do
        resources :bank_accounts, module: :configurations
    end

    resources :profiles do
        resources :bank_accounts, module: :profiles
    end

end

app/models/publicity.rb
class Publicity < ApplicationRecord

    has_one_attached    :avatar

    validates :description, presence: { message: 'Não pode estar em branco' }

    validates :start_date, :end_date, presence: true, if: :validate_date

    def validate_date
        errors.add(:base, "A data de início não pode ser maior ou igual à data de término.") if (start_date >= end_date)
    end

    def show_pub_on_client
        if self.status
            self.update_columns(status: false)
        else
            self.update_columns(status: true)
        end
        
    end
end

app/controllers/publicities_controller.rb
class PublicitiesController < ApplicationController
  before_action :set_publicity, only: [:show, :edit, :update, :destroy, :show_pub_on_client]

  # GET /publicities
  # GET /publicities.json
  def index
    @pagy, @publicities = pagy(Publicity.where.not(description: nil), items: 10)
  end

  # GET /publicities/1
  # GET /publicities/1.json
  def show
    @publicities = Publicity.all
    @publicitiesIsActive = Publicity.all.where(status: true)
    @publicitiesIsDisable = Publicity.all.where(status: false)
  end

  # GET /publicities/new
  def new
    @publicity = Publicity.new
  end

  def show_pub_on_client
    @publicity.show_pub_on_client
    redirect_to @publicity, notice: 'Publicidade ativada para o cliente.'
  end

  # GET /publicities/1/edit
  def edit
  end

  # POST /publicities
  # POST /publicities.json
  def create
    @publicity = Publicity.new(publicity_params)

    respond_to do |format|
      if @publicity.save
        format.html { redirect_to @publicity, notice: 'Publicidade criada com sucesso.' }
        format.json { render :show, status: :created, location: @publicity }
      else
        format.html { render :new }
        format.json { render json: @publicity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publicities/1
  # PATCH/PUT /publicities/1.json
  def update
    respond_to do |format|
      if @publicity.update(publicity_params)
        format.html { redirect_to @publicity, notice: 'Publicidade atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @publicity }
      else
        format.html { render :edit }
        format.json { render json: @publicity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publicities/1
  # DELETE /publicities/1.json
  def destroy
    @publicity.destroy
    respond_to do |format|
      format.html { redirect_to publicities_url, notice: 'Publicidade eliminada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publicity
      @publicity = Publicity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publicity_params
      params.require(:publicity).permit(:avatar, :description, :status, :start_date, :end_date)
    end

    def publicity_params_new
      params.require(:publicity).permit(:avatar, :description, :start_date, :end_date)
    end
end

app/helpers/publicities_helper.rb
module PublicitiesHelper
end

app/views/publicities/_form.html.erb
<%= simple_form_for(@publicity) do |f| %>
    <div class="content content-boxed">
        <div class="row">
            <div class="col-md-12">
                <!-- Updadtes -->
                <ul class="timeline timeline-alt py-0">
                    <li class="timeline-event">
                        <div class="timeline-event-icon bg-p3">
                            <i class="fa fa-edit"></i>
                        </div>
                        <div class="timeline-event-block block invisible" data-toggle="appear">
                            <div class="block-header">
                                <h3 class="block-title">Atualizar dados da publicidade</h3>
                            </div>

                            <%= f.error_notification %>
                            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

                            <div class="block-content">
                                <div class="row">
                                    <div class="col-md-6">
                                        <%= f.input :description, label: "Descrição da publicidade" %>
                                        <br>
                                        <%= f.input :avatar, label: "Imagem da publicidade" %>
                                    </div>
                                    <div class="col-md-6">
                                        <%= f.input :start_date %>
                                        <%= f.input :end_date %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>

                <div class="form-actions text-right">
                    <%= f.button :submit, "Atualizar", class: "btn btn-p3 btn-sm mr-2" %>
                </div>
                <!-- End Updadtes -->
            </div>
        </div>
    </div>

<% end %>

app/views/publicities/edit.html.erb
<!-- Hero -->
<div class="bg-image" style="background-image: url('/home.svg');">
    <div class="bg-black-50">
        <div class="content content-full text-center">
            <div class="my-3">
                <% if @publicity.avatar.attached? %>
                <%= image_tag(@publicity.avatar, class: "img-avatar img-avatar-thumb") %>
                <% else %>
                <img class="img-avatar img-avatar-thumb" src="/templete/assets/media/avatars/avatar13.jpg" alt="">
                <% end %>
            </div>
            <span class="text-white-75"><%= @publicity.description %></span>
        </div>
    </div>
</div>
<!-- END Hero -->

<%= simple_form_for(@publicity) do |f| %>
<div class="content content-boxed">
    <div class="row">
        <div class="col-md-12">
            <!-- Updadtes -->
            <ul class="timeline timeline-alt py-0">
                <li class="timeline-event">
                    <div class="timeline-event-icon bg-p3">
                        <i class="fa fa-edit"></i>
                    </div>
                    <div class="timeline-event-block block invisible" data-toggle="appear">
                        <div class="block-header">
                            <h3 class="block-title">Atualizar dados da publicidade</h3>
                        </div>

                        <%= f.error_notification %>
                        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

                        <div class="block-content">
                            <div class="row">
                                <div class="col-md-6">
                                    <%= f.input :description, label: "Descrição da publicidade" %>
                                    <br>
                                    <%= f.input :avatar, label: "Imagem da publicidade" %>
                                </div>
                                <div class="col-md-6">
                                    <%= f.input :start_date, label: "Data De Início" %>
                                    <%= f.input :end_date, label: "Data De Término" %>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>

            <div class="form-actions text-right">
                <%= f.button :submit, "Atualizar", class: "btn btn-p3 btn-sm mr-2" %>
                <%= link_to 'Cancelar', publicities_path, class: 'btn btn-sm btn-danger' %>
            </div>
            <!-- End Updadtes -->
        </div>
    </div>
</div>

<% end %>

app/views/publicities/index.html.erb
<!-- Hero -->
<div class="bg-image overflow-hidden" style="background-image: url('/home.svg');">
    <div class="bg-primary-dark-op">
        <div class="content content-narrow content-full">
            <div
                class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center mt-5 mb-2 text-center text-sm-left">
                <div class="flex-sm-fill">
                    <h1 class="font-w600 text-white mb-0 invisible" data-toggle="appear">Publicidades</h1>
                    <h2 class="h4 font-w400 text-white-75 mb-0 invisible" data-toggle="appear" data-timeout="250">Lista
                        de publicidades</h2>
                </div>
                <div class="flex-sm-00-auto mt-3 mt-sm-0 ml-sm-3">
                    <span class="d-inline-block invisible" data-toggle="appear" data-timeout="350">
                        <%= link_to new_publicity_path, class: "btn btn-sm btn-p3 px-4 py-2" do  %>
                        <i class="fa fa-plus mr-1"></i> Nova publicidade
                        <% end %>
                    </span>
                </div>
            </div>
        </div>
    </div>
  </div>
  <!-- END Hero -->
  
  <div class="content">
    <!-- Full Table -->
    <div class="block">
        <div class="block-header">
            <div class="block-options">
                <button type="button" class="btn-block-option">
                    <i class="si si-settings"></i>
                </button>
            </div>
        </div>
  
        <div class="block-content">
            <div class="table-responsive">
  
                <table class="table table-bordered table-striped table-center">
                    <thead>
                        <tr>
                            <th>Descrição</th>
                            <th>Data Início</th>
                            <th>Data Final</th>
                            <th class="text-center">Estado</th>
                            <th class="text-center">Acção</th>
                        </tr>
                    </thead>
  
                    <tbody>
                        <% @publicities.each do |publicity| %>
                        <tr>
                            <td><%= publicity.description %></td>
                            <td><%= publicity.start_date %></td>
                            <td><%= publicity.end_date %></td>
                            <td class="text-center">
                                <% if publicity.status %>
                                    <span class="badge badge-success">Activo</span>
                                <% else %>
                                    <span class="badge badge-danger">Inativo</span>
                                <% end %>
                            </td>
                            <td class="text-center">
                                <div class="btn-group">
                                    <% if current_user.admin? && false %>
                                        <%= link_to publicity, class: "btn btn-sm btn-danger js-tooltip-enabled", "data-toggle": "tooltip", "title": "Eliminar", "data-original-title": "Eliminar",
                                            method: :delete, data: { confirm: 'Tens a certeza?' } do %>
                                            <i class="fa fa-fw fa-trash"></i>
                                        <% end %>
                                    <% end %>
  
                                    <%= link_to publicity_path(publicity), class: "btn btn-sm btn-p3 js-tooltip-enabled", "data-toggle": "tooltip", "title": "Ver detalhes", "data-original-title": "Ver detalhes" do %>
                                        <i class="fa fa-fw fa-eye"></i>
                                    <% end %>
                                </div>
                            </td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
                <%== pagy_bootstrap_nav(@pagy).html_safe %>
                <br>
            </div>
        </div>
    </div>
    <!-- End Full Table -->
  </div>

app/views/publicities/new.html.erb
<!-- Hero -->
<div class="bg-image" style="background-image: url('/home.svg');">
    <div class="bg-black-50">
        <div class="content content-full text-center">
            <div class="my-3">
                <% if @publicity.avatar.attached? %>
                    <%= image_tag(@publicity.avatar, class: "img-avatar img-avatar-thumb") %>
                <% else %>
                    <img class="img-avatar img-avatar-thumb" src="/templete/assets/media/avatars/avatar13.jpg" alt="">
                <% end %>
            </div>
            <h1 class="h2 text-white mb-0"> Criar nova publicidade </h1>
        </div>
    </div>
</div>
<!-- END Hero -->

<%= simple_form_for(@publicity) do |f| %>
    <div class="content content-boxed">
        <div class="row">
            <div class="col-md-12">
                <!-- Updadtes -->
                <ul class="timeline timeline-alt py-0">
                    <li class="timeline-event">
                        <div class="timeline-event-icon bg-p3">
                            <i class="fa fa-edit"></i>
                        </div>
                        <div class="timeline-event-block block invisible" data-toggle="appear">
                            <div class="block-header">
                                <h3 class="block-title">Criar nova publicidade</h3>
                            </div>

                            <%= f.error_notification %>
                            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

                            <div class="block-content">
                                <div class="row">
                                    <div class="col-md-6">
                                        <%= f.input :description, label: "Descrição da publicidade" %>
                                        <br>
                                        <%= f.input :avatar, label: "Imagem da publicidade" %>
                                    </div>
                                    <div class="col-md-6">
                                        <%= f.input :start_date, label: "Data de início" %>
                                        <%= f.input :end_date, label: "Data de término" %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>

                <div class="form-actions text-right">
                    <%= f.button :submit, "Adicionar", class: "btn btn-p3 btn-sm mr-2" %>
                    <%= link_to 'Cancelar', publicities_path , class: "btn btn-danger btn-sm mr-2"%>
                </div>
                <!-- End Updadtes -->
            </div>
        </div>
    </div>
<% end %>

app/views/publicities/show.html.erb
<!-- Hero -->
<div class="bg-image" style="background-image: url('/home.svg');">
    <div class="bg-black-50">
        <div class="content content-full text-center">
            <div class="my-3">
                <% if @publicity.avatar.attached? %>
                    <%= image_tag(@publicity.avatar, class: "img-avatar img-avatar-thumb") %>
                <% else %>
                    <img class="img-avatar img-avatar-thumb" src="/templete/assets/media/avatars/avatar13.jpg" alt="">
                <% end %>
            </div>
            <span class="text-white-75"><%= @publicity.description %></span>
        </div>
    </div>
</div>
<!-- END Hero -->

<!-- Stats -->
<div class="bg-white border-bottom">
    <div class="content content-boxed">
        <div class="row items-push text-center">
            <div class="col-6 col-md-2">
                <div class="font-size-sm font-w600 text-muted text-uppercase">Total Pubs</div>
                <a class="link-fx font-size-h3" href="javascript:void(0)"><%= @publicities.count %></a>
            </div>
            <div class="col-6 col-md-2">
                <div class="font-size-sm font-w600 text-muted text-uppercase">Quant. Ativas</div>
                <a class="link-fx font-size-h3" href="javascript:void(0)"><%= @publicitiesIsActive.count %></a>
            </div>
            <div class="col-6 col-md-2">
                <div class="font-size-sm font-w600 text-muted text-uppercase">Quant. Inativas</div>
                <a class="link-fx font-size-h3" href="javascript:void(0)"><%= @publicitiesIsDisable.count %></a>
            </div>
            <div class="col-6 col-md-6 text-right">
                <%= link_to 'actualizar', edit_publicity_url(@publicity), class: "btn btn-sm btn-success" %>

                <% if current_user.admin? %>
                    <% if @publicity.status %>
                        <%= link_to 'Remover PUB', show_pub_on_client_url(@publicity), class: "btn btn-sm btn-info" %>
                    <% else %>
                        <%= link_to 'Ativar PUB', show_pub_on_client_url(@publicity), class: "btn btn-sm btn-info" %>
                    <% end %>
                <% end %>
                
                <%= link_to 'Voltar', publicities_url, class: "btn btn-sm btn-danger" %>
            </div>
        </div>
    </div>
</div>
<!-- End Stats -->

<!-- Page Content -->
<div class="content content-boxed">
    <div class="row">
        <div class="col-md-9 col-sm-12">
            <!-- Updates -->
            <ul class="timeline timeline-alt py-0">
                <li class="timeline-event">
                    <div class="timeline-event-icon bg-p3">
                        <i class="fa fa-briefcase"></i>
                    </div>
                    <div class="timeline-event-block block invisible" data-toggle="appear">
                        <div class="block-header">
                            <h2 class="block-title">Detalhes da publicidade</h2>
                        </div>

                        <div class="block-content">
                            <p><span class="font-w600 mb-2">Descrição: </span><span
                                    class="font-size-sm"><%= @publicity.description %></span></p>
                            <p><span class="font-w600 mb-2">Data de início: </span><span
                                    class="font-size-sm"><%= @publicity.start_date %></span></p>
                            <p><span class="font-w600 mb-2">Data de término: </span><span
                                    class="font-size-sm"><%= @publicity.end_date %></span></p>
                        </div>
                    </div>
                </li>

            </ul>
            <!-- END Updates -->
        </div>
    </div>
</div>
<!-- END Page Content -->

<%#= link_to 'Edit', edit_publicity_path(@publicity) %>
<%#= link_to 'Back', publicities_path %>